### ISSUE TITLE
Create templates for issue submission

### ISSUE THREAD

**Issue by dkyleward** [tfresource/tfresource-website#293]
@gregmacfarlane 
I'm taking this from the "Building a Stronger Community" section of the GitHub documentation: https://docs.github.com/en/enterprise-server@2.22/github/building-a-strong-community/configuring-issue-templates-for-your-repository

When someone hits the issue button, we can prompt them with info on how to submit a good issue. You can even have separate templates for bug reports, features requests, etc.

**Comment by ssmith55** [comment]
github.com/aequilbrae has a template

**Comment by gregmacfarlane** [comment]
This is an interesting idea, though I'm not sure how relevant it is. We don't need them to submit output logs or confirm their system specs. What do you think a template should say?

**Comment by dkyleward** [comment]
Some of the good ones I've seen are pretty simple. With that in mind, a 'feature' issue might be:

> Have an idea for a new topic? Please provide a paragraph describing the topic and why it should be included. Also, remember to nominate someone (possibly yourself) as a subject matter expert who could contribute.

If someone finds an error or bad info on our side, it might be:

> Found a problem? Please include the web address of the page and quote the original text. Then include what you think it should say.

These may not be the best, but I think it gives an idea of how a simple message can help people provide somewhat consistent issues.

**Comment by e-lo** [comment]
This is a great idea. @gregmacfarlane happy for you to assign to me.

**Comment by gregmacfarlane** [comment]
I believe that @e-lo did this already. Thanks!
