### ISSUE TITLE
Add "skim" definition

### ISSUE THREAD

**Issue by bettinardi** [tfresource/tfresource-website#318]
Reading the style guide I was pointed to the skimming page:
https://tfresource.org/topics/Skim_Matrix.html

It's very short and concise (great), but it was missing an explanation I was hoping for.  One of the things I always trip over is trying to explain to those new to modeling why the term "skim" is used.  It would be nice if this page could take a sentence or two to provide a little history on where the use of the term "skim" started.  I have my own thoughts and theories on this, but I have no actual knowledge.  I'm creating this issue in the hopes that someone has the history and can document it accordingly.

**Comment by gregmacfarlane** [comment]
@bettinardi see if you like this.

**Comment by bettinardi** [comment]
I'm not seeing the new text - feels like I'm doing something wrong

**Comment by gregmacfarlane** [comment]
It's in a branch and not live yet; can you look at [this commit](https://github.com/tfresource/website/commit/90dc1b6af46c23515c76a110bd9d9c65add89358)

**Comment by bettinardi** [comment]
Looks great - that works for me.  Maybe others might review and suggest improvements in the future, but I think that captures it well and addresses the issue I created.

**Comment by gregmacfarlane** [comment]
Rick and Bill Davidson are working on getting to the root of this.
