### ISSUE TITLE
Create a page for model estimation software

### ISSUE THREAD

**Issue by gregmacfarlane** [tfresource/tfresource-website#341]
Stuff like R (mlogit), python (Biogeme), Alogit, STATA, GAUSS

**Comment by gregmacfarlane** [comment]
@tfrossi sent initial draft via email to committee members.

**Comment by gregmacfarlane** [comment]
Page committed at f5372ebefa

**Comment by gregmacfarlane** [comment]
One last task is to link this page in the table of contents.

**Comment by vivekyadav26** [comment]
I added the link to page.
