### ISSUE TITLE
🛠️ Chore: Change repo name from website --> something more identifiable amidst many "website" folders.

### ISSUE THREAD

**Issue by e-lo** [tfresource/tfresource-website#362]
As a developer/contributor, I would appreciate the repository to have a unique name which, when cloned or forked, appears as a uniquely named folder or repo respectively.

**Comment by e-lo** [comment]
Suggested repo name: `tfresource-website`

**Comment by gregmacfarlane** [comment]
I also think this would be a good idea, but I don't know how stitched into it everything is.

**Comment by gregmacfarlane** [comment]
@billyc can do this while he is working on with #366
