### ISSUE TITLE
🌱 Topic: Uncertainty

### ISSUE THREAD

**Issue by e-lo** [tfresource/tfresource-website#375]
## User Story

* As a practitioner (like [Flavia](https://github.com/flaviatsang), who requested  resources on this)
* I would like to have a description of practical approaches to characterizing uncertainty in our forecasts
* So that I can convey the uncertainty of various metrics to decision-makers

## Existing Resources

- [TMIP EMAT](https://tmip-emat.github.io/)
- Probably some research papers

Associated TF Resource Pages:  

*couldn't find associated ones*

## Issue Ready Checklist

- [ ] Sufficiently defined

**Comment by gregmacfarlane** [comment]
I have a student working on this topic; I could ask her to write a summary of the literature she has found as a starter. Where do you think the page should be slotted in the outline?

**Comment by ClarissaLiv** [comment]
I'm trying to write my thesis on a related topic, I'd be interested in helping out on this.

**Comment by gregmacfarlane** [comment]
Probably need a few different approaches: 

  - A page on sources of uncertainty in model design (statistical error, inputs) @ClarissaLiv 
  - A page / paragraph describing the design of EMAT
  - A page on scenario analysis and how to consider (or ignore / deal with) black swan events @tfrossi @brigar

**Comment by brigar** [comment]
We have some content on decision making under deep uncertainty (application context) that may be useful

**Comment by gregmacfarlane** [comment]
@bhargavasana is going to put the write-up he did for #387 in as new page for the moment, until the content charrette can happen.
