### ISSUE TITLE
🌱 Topic: Equity Analysis

### ISSUE THREAD

**Issue by bricegnichols** [tfresource/tfresource-website#377]
Topic on equity analyses based on travel model outputs, motivations, current state of the practice and missing pieces. 

## User Story

* As a practitioner (someone building models and evaluating results),
* I would like to know the best practices for equity analysis and understand the gaps 
* So that I can apply the tools appropriately and focus development on critical data/model needs

## Context
- Equity analysis is becoming central to forecasting and planning work, with some agencies centering their work around equity indicators of race, income, language, and others
- For many practitioners, there is often a disconnect between what the models provide and what planners are concerned about (people, specifically historically marginalized groups). For example, are project benefits and costs equitably distributed across race/income/other factors?
- Existing models are often missing important components that allow for proper analysis by planners. Some topics related to modeling specifically on how and why to:
    - control for race in synthetic population,
    - include race variables in key models like auto ownership,
    - forecast future populations that include race (currently little research or guidance on feasibility of this topic)  
- This topic can focus on motivations/need for equity analysis, existing best practices, and identifying technical challenges specific to travel models

## Existing Resources
- [TCRP 214](http://nap.edu/25860)
- A lot of people are working on this topic, so I'm sure there are some key committee members that we can leverage. 

## Issue Ready Checklist

- [x] Sufficiently defined

**Comment by gregmacfarlane** [comment]
Other resources: Tierra Bills, Jonathan Erlich, @lmz , @bhargavasana

**Comment by bricegnichols** [comment]
Working doc available here, send me a message if you want access: https://docs.google.com/document/d/162hJ36IEOpxf22Q3zCiQ0P3af0AWstkeRWQi-iSfWE0/edit?usp=sharing

**Comment by gregmacfarlane** [comment]
Discussion from September meeting: add some structure, and put on the site.

**Comment by gregmacfarlane** [comment]
Merged in #396
