### ISSUE TITLE
🌱 Topic: Learning Pathway

### ISSUE THREAD

**Issue by e-lo** [tfresource/tfresource-website#383]
## User Story

* As a travel modeling manager
* I would like to have a resource/link to point new employees to
* So that they can learn step-by-step how travel modeling works in the real world for the context that we are working in (statewide, MPO, development, application, etc) as opposed to sending them to "the encyclopedia" version of this website.

## Context

The site has an overwhelming amount of information which is great if you knew "what you need to learn about" but not if you don't.

## Existing Resources

Examples learning pathways: 

- [Linked In](https://www.linkedin.com/learning/search?entityType=LEARNING_PATH) 
- [Coursera](https://blog.coursera.org/introducing-career-learning-paths/)

*note most of these are for individual courses - I'm guessing there are good examples with links to articles as well*

Associated TF Resource Pages:  

* ...  

## Issue Ready Checklist

- [ ] Sufficiently defined

**Comment by gregmacfarlane** [comment]
I think this insight is correct. Multiple conversations like this have basically led to the question of whether we need a manual rather than an encyclopedia. Our efforts to create an outline over 2020 have pushed us in this direction. Do you have something different in mind?

**Comment by gregmacfarlane** [comment]
@bricegnichols is going to use TF Resource to onboard a new employee. Look for pain points, what is the most useful thing / what are not helpful?

**Comment by gregmacfarlane** [comment]
Let's have Brice talk about the learning path at the October meeting

**Comment by gregmacfarlane** [comment]
@strattonma brought up the idea to have contacts and references for further contact

**Comment by bricegnichols** [comment]
I have a draft for this, but I'm not sure where it needs to live in the wiki. Should I add it as a new page and we can figure out how to organize it into the website later?

https://docs.google.com/document/d/1WG1n-yQ3DPuWHFPEI0LvlFF9M1Egg5Gu3D3owrWLRjU/edit?usp=sharing

Please send a request for edit access if you want to add/change anything.

**Comment by gregmacfarlane** [comment]
I think we need to make this a TF Resource page called "Start Here" or something like that. Then, have a button on the home page that will direct to this.

**Comment by bricegnichols** [comment]
Published: https://github.com/tfresource/tfresource-website/blob/source/topics/Getting_Started.md
